### ISSUE TITLE
Ignore docstrings when calculating function length

### ISSUE THREAD

**Issue by thomasjbradley** [best-doctor/flake8-functions#1]
I set my `max-function-length` really low, `25`, to put some real pressure on writing short functions. But the problem I’m running into is that Docstrings are inflating the function’s length.

I was thinking, around this line, we could calculate the length of the docstring:
https://github.com/best-doctor/flake8-functions/blob/master/flake8_functions/checker.py#L29

```py
docstring_rows = len(func_def.__doc__.strip().split("\n"))
```

And subtract that when calculating the length on this line:
https://github.com/best-doctor/flake8-functions/blob/master/flake8_functions/checker.py#L36

Something like this:
```py
'length': function_last_statement.lineno - function_start_row - docstring_rows + 1,
```

**Comment by Melevir** [comment]
Fixed. Please, upgrade to version 0.0.3

**Comment by thomasjbradley** [comment]
Thanks so much! 

But I’m still getting problems when the Docstring has RST inside it.

Something like this:

```py
def my_func():
    """
    This is an introduction.

    And a list of things:
    - Thing 1
    - Thing 2
    - Thing 3
    """
    return True
```

This would over report by 3 lines, seems to be equal to the list lines in the Docstring. Any thoughts?

**Comment by Melevir** [comment]
@LerikP dramatically improved my solution. Please, try v0.0.4 and write if it works wrong.

**Comment by thomasjbradley** [comment]
That seems to be working as I expect now. Thanks so much for you help!
